version: '3.9'

networks:
  test_network:

services:
  proxy:
    build:
      context: ../
      dockerfile: ./HttpToGrpcProxy/Dockerfile
    environment:
      - HTTP_PORTS=80
    ports:
      #- "80:5000" # appearently there is no need to open http port, it is accessible inside docker compose
      - "6000:6000" # port for grpc client to connect
    networks:
      default:                      # not sure if this is a bug, but with single nework aliases are not added
      test_network:
        aliases:
          - first.example.com       # make some aliases so request from test_app would be captured by proxy
          - second.example.com

  test_app:
    build:
      context: ./
      dockerfile: ./TestApp/Dockerfile
    ports:
      - "8080:80"
    networks:
      test_network:
        aliases:
          - just_tests
